Fix `switch_branch': undefined method `blank?' for "":String (NoMethodError) (#337)
* fix `switch_branch': undefined method `blank?' for "":String (NoMethodErro)

* change to stub #switch_branch method